(define (foo a b c) 
  (define (sum-of-squares x y)
	(+ (* x x) (* y y))
  )
	(cond ((= (max a b) (max b c)) (sum-of-squares b (max a c)))
		  ((= (max a c) (max a b)) (sum-of-squares a (max b c)))
		  (else (sum-of-squares c (max a b)))
    )
)
